export default {
  id: "folktales",
  title: "Folk tales",
  emoji: "🦉",
  text: `A thirsty crow once flew across a dry field searching for water. After a long search, the crow spotted a tall clay pot near an old wall. Water sat at the very bottom of the narrow pot, far out of reach. The crow pushed its beak deep into the pot, but its beak could not reach the water. The crow tried tipping the pot over, but the pot was far too heavy to move. Tired and thirsty, the crow sat beside the pot and thought carefully about the problem. Nearby, small pebbles lay scattered across the dusty ground. The clever crow picked up one pebble and dropped it into the pot. Slowly, the crow picked up pebble after pebble and dropped each one inside. With every pebble, the water inside the pot rose a little higher. After many trips, the water finally rose close enough for the crow to drink. The crow drank happily and then flew off, refreshed and proud of its clever plan. A patient mind can solve problems that strength alone cannot.

A wide river once flowed quickly through a green valley toward the sea. Small clay houses stood along the riverbank, and a young farmer lived in one of them. The farmer often begged the river to slow down and rest for a while. The river never stopped, since rivers must always flow toward the sea. One year, heavy rain fell across the hills above the valley. The river rose fast, filling its banks and rushing toward the farmer's fields. The farmer had built a small canal months earlier, just in case of a flood. When the river rose, the canal carried the extra water safely around the fields. Crops that would have been washed away instead stood safe and dry. The farmer later told his children that rivers do not wait for anyone. He explained that people must prepare early, before trouble ever arrives. Neighbors who had not built canals lost much of their harvest that year. From then on, the whole village worked together to dig canals every dry season. Prepare before trouble arrives, because a river will not wait for you.

A busy market once filled a narrow street with noise, color and crowds. Sellers called out prices for fruit, cloth, pots and shiny bangles. Carts loaded with mangoes and melons rolled slowly between the crowded stalls. Among the crowd, a thief watched quietly for a chance to grab something valuable. He had drifted from stall to stall since early morning, looking for an easy target. A small girl stood beside her mother's stall, arranging fresh oranges in neat rows. She hummed quietly to herself as she worked, seeming to notice little around her. The thief slipped closer, eyeing a bag of coins left near the edge of the stall. He moved slowly, careful not to knock over any baskets or draw attention. As the thief reached for the bag, the girl looked up and noticed his moving hand. Without shouting, the girl calmly stepped in front of the bag and smiled at him. The thief froze, unsure whether the girl had already called for help. A moment later, the girl's uncle walked over, drawn by her steady, watchful stare. The uncle asked the thief plainly why his hand hovered so close to the coins. The thief quickly backed away and disappeared into the crowded street. Word of the clever girl spread through the market before the afternoon had ended. Other sellers began asking her to keep an eye on their stalls too. The girl's mother praised her daughter for staying calm and alert. She reminded her daughter that a careful eye can stop trouble before it grows. Even a child's quiet attention can protect what grown-ups almost lose.`,
};
