export default {
  id: "history",
  title: "South Asian history",
  emoji: "🏛️",
  text: `The Indus Valley people built cities more than four thousand years ago. Their two biggest cities were Mohenjo-daro and Harappa. Both cities stood in the wide Indus river valley. The streets ran in straight lines and crossed at right angles. Houses were built from baked bricks of the same size. Many homes had their own wells and bathing rooms. Covered drains ran under the streets to take dirty water away. This was one of the best drainage systems in the ancient world. Traders used small stone seals carved with animals and signs. Ships from the Indus Valley likely reached lands as far as Mesopotamia. Around 1900 BCE the great cities slowly emptied out. Rivers may have changed course and farming grew harder. The people scattered into smaller villages across the region.

New groups of people arrived from Central Asia after the Indus cities declined. They spoke an early form of Sanskrit and are called the Vedic people. They composed hymns and prayers that were later collected into the Vedas. These hymns praised gods of the sky, the sun, fire and rain. Cattle were a sign of wealth and were carefully counted and guarded. Families lived in small kingdoms ruled by chiefs and later by kings. Over time these people learned to use iron tools and weapons. Iron ploughs let farmers clear forests and grow more food. Bigger kingdoms called Mahajanapadas grew across the northern plains. Priests, warriors, traders and workers formed different groups in society. This system of groups later hardened into castes.

Chandragupta Maurya built a large empire around 321 BCE. His capital was the city of Pataliputra in the east. His grandson Ashoka became one of the most famous rulers of ancient India. Ashoka fought a hard war against the kingdom of Kalinga. After seeing the suffering of that war he turned to Buddhism. He then chose peace and kindness over further conquest. Ashoka placed stone pillars and edicts across his huge empire. Some of these edicts have been found in the northwest, in what is now Pakistan. He asked officials to treat people fairly and to protect animals. The Maurya empire slowly broke apart after Ashoka died.

The Gandhara region lay around the Peshawar valley in the northwest. It became a center of a special style of art called Gandhara art. This art mixed Greek forms with local Buddhist ideas after old Greek settlers stayed in the region. Kushan kings later ruled Gandhara and supported this art and Buddhist learning. Not far from Gandhara stood the ancient city of Taxila. Taxila was famous as a center of learning for the whole region. Students came from distant lands to study medicine, grammar and philosophy there. Taxila had teachers, halls and stupas spread across a wide area. The ruins of Taxila can still be seen near Rawalpindi today.

In 712 CE a young Arab general named Muhammad bin Qasim marched into Sindh. He led his army for the Umayyad rulers who sent him from Damascus. His forces met the army of Raja Dahir, the ruler of Sindh. Muhammad bin Qasim defeated Raja Dahir in a hard battle near the Indus. After this victory Sindh came under Arab and later Muslim rule. Many historians see this as the start of Muslim rule in the region. Muhammad bin Qasim set fair terms for the local people who stayed. Trade along the Indus grew stronger under the new rulers.

Mahmud of Ghazni led many raids into South Asia in the early eleventh century. He ruled from the city of Ghazni in what is now Afghanistan. His armies crossed the mountains and reached deep into the Punjab. Lahore became an important city for the Ghaznavid rulers during this time. Later, when Ghazni fell to rivals, Lahore even served as their last capital. Scholars gathered at the Ghaznavid court, including the great writer Al-Biruni. Al-Biruni studied the languages, science and customs of South Asia closely. Lahore grew into a busy center of trade and learning under Ghaznavid rule.

Muhammad Ghori extended Muslim rule further into the northern plains after Mahmud. His general Qutb-ud-din Aybak became the first sultan of Delhi in 1206. This began the long period known as the Delhi Sultanate. Several dynasties ruled one after another from Delhi over the next three centuries. These included the Slave dynasty, the Khalji dynasty, the Tughlaq dynasty and later the Lodi dynasty. The tall tower called the Qutub Minar was built during this early period. Delhi Sultanate rulers built forts, mosques and canals across northern India. Trade routes linked Delhi with Central Asia, Persia and the Arabian Sea coast. The Delhi Sultanate slowly weakened after repeated invasions from the northwest.

Babur was a prince from Central Asia descended from Timur and Genghis Khan. He lost his first small kingdom and looked south for new land. In 1526 Babur met Sultan Ibrahim Lodi at the first battle of Panipat. Babur used cannons and skilled riders to win a clear victory there. This victory ended the Delhi Sultanate and began the Mughal empire. Babur then ruled from Delhi and Agra for a short time before he died.

Babur's son Humayun took the throne next but faced many troubles. A skilled rival named Sher Shah Suri defeated Humayun and took his lands. Humayun fled west to Persia and lived there for several hard years. With Persian help he returned and won back his throne in 1555. Humayun died just a year later after a fall near his library. His young son Akbar then became the new emperor of the Mughal empire.

Akbar ruled the Mughal empire from 1556 to 1605 and greatly expanded it. He built a stunning new capital city at Fatehpur Sikri near Agra. Fatehpur Sikri had grand courts, a mosque and a tall gateway called the Buland Darwaza. Akbar formed strong alliances with several Rajput kingdoms through marriage and careful diplomacy. He removed the special tax that non-Muslim subjects once had to pay. Akbar also created a new set of ideas called Din-i Ilahi. Din-i Ilahi tried to blend the best parts of many faiths together. He invited scholars of different religions to debate at his court. Akbar's fair rule and strong army held the huge Mughal empire together. Later, the capital moved away from Fatehpur Sikri because water there ran short.

Akbar's son Jahangir ruled the Mughal empire from 1605 to 1627. Jahangir loved gardens, paintings and rare animals from distant lands. He is remembered for a golden chain of bells outside his palace. Any person could pull the chain to ask the emperor for justice. His wife, the clever and powerful Nur Jahan, helped run the empire. Under Jahangir, artists painted detailed pictures of birds, flowers and court life.

Shah Jahan became the Mughal emperor in 1628 and ruled for thirty years. He is best remembered for the Taj Mahal, built in Agra. Shah Jahan built the Taj Mahal for his wife Mumtaz Mahal. White marble and careful patterns cover every wall of the Taj Mahal. Shah Jahan also added grand halls and gates to Lahore Fort. Near Lahore he laid out the beautiful Shalimar Gardens with rows of fountains. In Delhi he built the Red Fort and the great Jama Masjid mosque. Shah Jahan's rule is often called the golden age of Mughal building. Skilled workers from across the empire and beyond worked on these great projects.

Aurangzeb, Shah Jahan's son, ruled the Mughal empire from 1658 to 1707. Under Aurangzeb the Mughal empire reached its largest size ever. Long wars in the Deccan region drained the treasury for many years. Aurangzeb lived a simple life but ruled with a strict hand. After his death in 1707 the vast Mughal empire began to weaken fast.

Weak emperors followed Aurangzeb and struggled to hold the empire together. In 1739 the Persian ruler Nadir Shah invaded and sacked the city of Delhi. He carried off the famous Peacock Throne and countless other treasures. Regional powers such as the Marathas and various Nawabs grew stronger and bolder. Sikh groups in the Punjab also grew into a strong military force. The once mighty Mughal empire now controlled little beyond the city of Delhi.

Ranjit Singh united the Sikh groups of the Punjab into one strong state. He became Maharaja and ruled from his capital at Lahore. Under Ranjit Singh the Sikh empire stretched across the Punjab and beyond. He built a modern army trained partly by European officers. Ranjit Singh respected people of every faith across his kingdom. After his death in 1839 the Sikh empire quickly grew weak and divided. Two hard wars against the British followed within the next ten years. The British annexed the Punjab and the Sikh empire in 1849.

The East India Company first arrived in South Asia to trade in cloth and spices. Over time the company built forts, trained soldiers and gathered local allies. In 1757 the company won the battle of Plassey in Bengal. That victory let the company take real political power over Bengal. Company rule then spread west and south across the subcontinent. Local rulers signed treaties or lost wars against company forces. By the early 1800s the East India Company controlled vast territories. The company collected taxes, ran courts and shaped trade to suit its own interests.

In 1857 soldiers and common people rose up against East India Company rule. New rifle cartridges, land taxes and broken promises had angered many groups. The uprising spread quickly across northern India before it was crushed. Delhi, Lahore and other cities saw fighting between rebels and company forces. After the uprising the British Crown took direct control of the region. This new period of direct British rule is often called the British Raj. The East India Company itself was closed down soon after these events.

Sir Syed Ahmad Khan worked hard to help Muslims recover after 1857. He believed modern education would help his community move forward. In 1875 he founded a college at Aligarh for Muslim students. This college later grew into the well known Aligarh Muslim University. Students there studied science and English alongside Islamic teachings and Urdu. Sir Syed's ideas shaped how many Muslim leaders later thought about education and unity.

Muslim leaders formed the All-India Muslim League in Dhaka in December 1906. The League aimed to protect the political rights of Muslims in British India. It grew over the years into the main voice for Muslim political demands. Many young lawyers and thinkers joined the League during its early decades.

The poet and thinker Allama Iqbal addressed the Muslim League in Allahabad in 1930. In his address Iqbal spoke of a separate homeland for Muslims. He suggested that the northwestern regions could form such a homeland. Iqbal's poetry and speeches inspired many who later worked for Pakistan. His ideas gave a clear shape to hopes that had been growing for years.

On 23 March 1940 the Muslim League passed the Lahore Resolution. The resolution called for independent states for Muslims in the northwestern and eastern zones. Huge crowds gathered in Lahore to hear speeches about the resolution. This day is still remembered every year across Pakistan as a key moment. The Lahore Resolution set a clear political goal for the years that followed.

Muhammad Ali Jinnah led the Muslim League through its final and hardest years. He is known across Pakistan as the Quaid-e-Azam, or great leader. Jinnah negotiated firmly with British officials and with Congress leaders. He argued that Muslims needed their own separate and independent country. Jinnah's clear legal mind and steady will guided the League through tense talks.

On 14 August 1947 Pakistan became an independent country at last. The British left South Asia and divided the land into two new countries. Millions of people moved across the new borders in the months that followed. Families left homes, farms and shops built over many generations. Despite great hardship, the new country of Pakistan began building its own institutions. Jinnah became the first Governor-General of the new state of Pakistan.

Karachi served as the first capital of the new country of Pakistan. Government offices, embassies and the first parliament all opened in Karachi. The city grew fast as officials, workers and refugees arrived from many places. Years later the capital moved first to Rawalpindi and then to a new city. That new planned city, built north of Rawalpindi, was named Islamabad. Even after the capital moved, Karachi remained the largest city and busiest port. Pakistan's history, from the old Indus cities to 1947, still shapes the country today.`,
};
